---
title: "analysis_participant1"
author: "Jules Roboz"
date: "2025-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Gebruiker/Documents/Masters CCS/Year1/Block12/Methods in CCS/algebra/methodsccs-group3/methodsccs-group3/methodsccs_eyetracking/")

#load packages
require(PupilPre)
require(eyelinker)
require(plyr)
require(dplyr)
```


```{r}
source("./asc_to_pupilpre.R")
```
```{r}
path_to_file <- "sub3_modified.asc"
raw_dat <- read.asc(path_to_file)
```
```{r}
#head(raw_dat$raw)
head(raw_dat$msg, 20)
#raw_dat$fix
```
```{r}
label <- "sub3" # Some subject identifier
recorded_eye <- "Left"
trial_start_msg <- "var StartTrial [0-9]+" # Trial begin pattern
id_pattern <- "StartTrial " # Trial pattern used for trial index
trial_end_msg <- "EndTrial [0-9]+" # Trial end pattern
```
```{r}
ppl_pre_dat <- asc_to_pupilpre(path_to_file,
                               label,
                               recorded_eye,
                               trial_start_msg,
                               id_pattern,
                               trial_end_msg)
```

```{r}
head(ppl_pre_dat$pplpreData)
#head(ppl_pre_dat$rawMessages)
```
```{r}
#for baselining purposes, I wanna shift in_trial to be 400ms before
# Defensive conversion of in_trial into a logical vector
get_logical_in_trial <- function(x) {
  # if it's a list-column, unlist first
  if (is.list(x)) x <- unlist(x, use.names = FALSE)
  # if factor or other, make character first to avoid weird factor-to-logical coercion
  if (is.factor(x)) x <- as.character(x)
  # if character (e.g. "TRUE"/"FALSE"), coerce to logical
  if (is.character(x)) x <- as.logical(x)
  # finally ensure logical type
  x <- as.logical(x)
  # replace NA with FALSE (you can change behaviour if desired)
  x[is.na(x)] <- FALSE
  x
}

# Use the helper on your dataframe
in_trial_vec <- get_logical_in_trial(ppl_pre_dat$pplpreData$in_trial)

# sanity checks
stopifnot(length(in_trial_vec) == nrow(ppl_pre_dat$pplpreData))

# compute sample spacing in ms (median to be robust to small irregularities)
sample_ms <- median(diff(ppl_pre_dat$pplpreData$TIMESTAMP), na.rm = TRUE)
if (!is.finite(sample_ms) || sample_ms <= 0) stop("TIMESTAMP spacing could not be determined.")

# how many samples = 400 ms
shift_n <- ceiling(400 / sample_ms)

# find start indices: locations where FALSE -> TRUE
# using integer diff: 0->1 gives diff == 1
start_idx <- which(diff(as.integer(in_trial_vec)) == 1) + 1

# copy and apply shifts
new_in_trial <- in_trial_vec
for (i in start_idx) {
  from <- max(1, i - shift_n)
  to   <- i - 1
  if (from <= to) new_in_trial[from:to] <- TRUE
}

# save result to new column
ppl_pre_dat$pplpreData$in_trial_shifted <- new_in_trial

# quick verification
cat("Original TRUE count:", sum(in_trial_vec), "\n")
cat("Shifted TRUE count:", sum(new_in_trial), "\n")
cat("Number of detected starts:", length(start_idx), "\n")


head(ppl_pre_dat$pplpreData)
```
```{r}
#checking that the shifting was done correctly, it was

library(dplyr)

df_check <- ppl_pre_dat$pplpreData %>%
  group_by(TRIAL_INDEX) %>%
  summarise(
    old_start_ts = TIMESTAMP[which(in_trial == TRUE)[1]],
    new_start_ts = TIMESTAMP[which(in_trial_shifted == TRUE)[1]],
    shift_ms     = old_start_ts - new_start_ts,
    .groups = "drop"
  )

summary(df_check$shift_ms)

```


```{r}
ppl_pre_dat$pplpreData$in_trial <- ppl_pre_dat$pplpreData$in_trial_shifted
ppl_pre_dat$pplpreData$in_trial_shifted <- NULL
dat <- ppl_pre_dat$pplpreData[ppl_pre_dat$pplpreData$in_trial,]
str(dat)
```
```{r}
dat_aligned <- align_msg(dat, Msg = "StartTrial")
#str(dat_aligned)
dat_time <- create_time_series(dat_aligned, Adjust = 0)
```
```{r}
check_msg_time(dat_time, Msg = "StartTrial", ReturnData=T) #all zeros so it's good
#check_msg_time(dat_time, Msg = "Response given [0-9]", ReturnData = T)
```
```{r}
dat2 <- ppl_select_recorded_eye(data = dat_time, Recording = "LorR", WhenLandR = "Left")
```

```{r}
with(dat2,plot(Gaze_X,Gaze_Y))
```
```{r}
dat3 <- recode_off_screen(data = dat2, ScreenSize = c(1280, 1024))
```
```{r}
with(dat3,plot(Gaze_X,Gaze_Y, xlim = c(0, 1280), ylim = c(0, 1024)))
```
```{r}
#blink_summary(dat3, Summary = "Event")
NA_summary(dat3, Summary = "Event", PupilColumn="Pupil")
```
```{r}
dat4 <- clean_blink(dat3, BlinkPadding = c(170, 170), Delta = 5,
                    MaxValueRun = 5, NAsAroundRun = c(2,2),
                    LogFile = "BlinkCleanupLog.rds")
```


```{r}
#remove data points where the popup appeared  (14, 15, 16, 17) and practice trials (1, 2, 3, 4)
#dat4 <- subset(dat4, !(TRIAL_INDEX %in% c(1, 2, 3, 4, 14, 15, 16, 17)))
bad_events <- c("sub3.1", "sub3.2", "sub3.3", "sub3.4")

dat4 <- dat4[! as.character(dat4$Event) %in% bad_events, ]
dat4$Event <- droplevels(dat4$Event)

```
```{r}
#table(dat4$TRIAL_INDEX)
plot_compare_app(dat4)
```
```{r}
dat5 <- interpolate_NAs(dat4, Method = "linear", XandY = T, MinData = 2)
plot_compare_app(dat5)
```

```{r}
dat6_p3 <- baseline(dat5, BaselineWindow = c(0, 100), BaselineType = "Subtraction")
```

```{r}
saveRDS(dat6_p3, file = "FinalDat3.rds", compress = "xz")
```


```{r}
p1dat <- readRDS("FinalDat.rds")
p2dat <- readRDS("FinalDat2.rds")
p3dat <- readRDS("FinalDat3.rds")
```

```{r}
head(p1dat)
head(p2dat)
head(p3dat)

full_dataset <- rbind(p1dat, p2dat, p3dat)
str(full_dataset)
```


```{r}
ppl_plot_avg(data = full_dataset, xlim = c(0, 5000), Column = "Pupil",
             Condition1 = NULL, Condition2 = NULL, Cond1Labels = NA, 
             Cond2Labels = NA, ErrorBar = FALSE, ErrorBand=TRUE, PupilPreTheme = TRUE) 
```
```{r}
full_dataset$condition <- 0 #ini at 0
cond <- 'none'
for(i in 1:length(full_dataset$Subject)){ #for each sample in our dataset
    tmp <- full_dataset$SAMPLE_MESSAGE[i] #check whether there's a message
    if(!is.na(tmp)){ #if there is
        tmp <- regexpr( 'difficulty [0-9]+', full_dataset$SAMPLE_MESSAGE[i]) #check whether 'difficulty ##' is in the message
        if(!is.na(tmp) && tmp != -1){ #if so
            cond <- regmatches(full_dataset$SAMPLE_MESSAGE[i],tmp)        
            cond <- as.numeric(regmatches(cond,regexpr("[0-9]+",cond))) #set 'cond' to the type 
        }
    }
    full_dataset$condition[i] <- cond #and add this to the new condition variable that we added above
}
full_dataset$difficulty <- as.factor(full_dataset$condition)
full_dataset <- full_dataset[full_dataset$difficulty != "none", ]

#now we can plot:
ppl_plot_avg(data = full_dataset, xlim = c(0, 5000), Column = "Pupil", 
             Condition1 = "difficulty", Condition2 = NULL, 
             ErrorBar = FALSE, ErrorBand=TRUE, PupilPreTheme = FALSE)
```
```{r}
saveRDS(full_dataset, file = "FinalFullDat.rds", compress = "xz")
```
```{r}
full_dataset <- readRDS("FinalFullDat.rds")
```


```{r}
#check to make sure difficulty is calculated correctly, it is
#table(dat6$difficulty, dat6$TRIAL_INDEX)

#head(dat6, 10)

```
```{r}
library(mgcv)
library(itsadug)
#Create model
#m1 = bam(Pupil ~ difficulty + s(Time, by=difficulty), data=dat6, method="ML")

#m1b = bam(Pupil ~ difficulty + s(Time, by=difficulty) + s(Time, Subject, bs='fs', m=1), data=dat6, method="ML")

#Jacolien's suggestion:
full_dataset$DiffSubj = interaction(full_dataset$difficulty, full_dataset$Subject, drop=T)
m1c = bam(Pupil ~ difficulty + s(Time, by=difficulty) + s(Time, DiffSubj, bs='fs', m=1), data=full_dataset, discrete=TRUE)

summary(m1c)

par(mfrow=c(1,2))

# PLOT 1
plot(m1c)

# PLOT 2
plot_smooth(m1c, view="Time", plot_all=c("difficulty", "Subject"))
```

